version: '3.4'

services:
  postgres:
    image: postgres

  mongodb:
    image: mongo

  rabbitmq:
    image: rabbitmq:management

  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile

  searchservices:
    image: ${DOCKER_REGISTRY-}searchservices
    build:
      context: .
      dockerfile: src/SearchServices/Dockerfile

  gatewayservice:
    image: ${DOCKER_REGISTRY-}gatewayservice
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile

  biddingservice:
    image: ${DOCKER_REGISTRY-}biddingservice
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile

volumes:
  postgres_db:
  mongo_db:  
