version: '3.4'

services:
  postgres:
   container_name: postgresql
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgrespw
    - POSTGRES_DB=PostgresDb
   restart: always
   ports:
   - "5432:5432"
   volumes:
    - postgres_db:/var/lib/postgresql/data

  mongodb:
   container_name: mongodb
   environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=mongopw
    - MONGO_INITDB_DATABASE=MongoDb
   restart: always
   ports:
   - "27017:27017"
   volumes:
    - mongo_db:/data/db

  rabbitmq:
    container_name: rabbitmq
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
 