apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgresql
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
         - name: POSTGRES_PASSWORD
           value: postgrespw   
        ports:
        - containerPort: 5432
        volumeMounts:
         - mountPath: /var/lib/postgresql/data
           name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
           claimName: postgres-claim
---
# for internal 
apiVersion: v1
kind: Service
metadata:
  name: postgres-clusterip
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
# for external
apiVersion: v1
kind: Service
metadata:
  name: postgres-np
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30001

